import 'package:trekntread/Model/product.dart';


List<Product> mockProducts = [
  Product(
    id: '1',
    name: 'Air Max 90',
    price: 2290,
    originalPrice: 2690,
    imageUrl: 'https://trekntread.com/tenancy/assets/636/photo1709618571.jpeg',
    discount: 15,
    categoryId: 'sneakers',
    brand: 'Nike',
    description: 'Classic Nike Air Max 90 sneakers',
    stockQuantity: 10,
    tags: ['sneakers', 'nike', 'trending'],
    attributes: {
      'sizes': ['40', '41', '42', '43', '44'],
      'colors': ['red', 'black'],
    },
  ),
  Product(
    id: '2',
    name: 'Nike Jordan',
    price: 3990,
    originalPrice: 4590,
    imageUrl: 'https://trekntread.com/tenancy/assets/999/photo_2024-05-08_10-50-02.jpg',
    discount: 13,
    categoryId: 'basketball',
    brand: 'Nike',
    description: 'Iconic Nike Jordan basketball shoes',
    stockQuantity: 8,
    tags: ['basketball', 'nike', 'premium'],
    attributes: {
      'sizes': ['40', '41', '42', '43', '44'],
      'colors': ['white', 'black'],
    },
  ),
  Product(
    id: '3',
    name: 'Adidas Ultraboost',
    price: 3790,
    originalPrice: 4190,
    imageUrl: 'https://trekntread.com/tenancy/assets/995/photo_2024-05-02_19-03-45.jpg',
    discount: 10,
    categoryId: 'running',
    brand: 'Adidas',
    description: 'High-performance running shoes',
    stockQuantity: 12,
    tags: ['running', 'adidas', 'ultraboost'],
    attributes: {
      'sizes': ['40', '41', '42', '43', '44'],
      'colors': ['blue', 'gray'],
    },
  ),
  Product(
    id: '4',
    name: 'Puma RS-X',
    price: 2590,
    originalPrice: 2990,
    imageUrl: 'https://static-01.daraz.com.bd/p/6d2c58de0d8a05fa876954e4c352bd98.jpg',
    discount: 12,
    categoryId: 'casual',
    brand: 'Puma',
    description: 'Puma RS-X stylish sneakers',
    stockQuantity: 15,
    tags: ['casual', 'puma', 'fashion'],
    attributes: {
      'sizes': ['40', '41', '42', '43', '44'],
      'colors': ['white', 'black'],
    },
  ),
  Product(
    id: '5',
    name: 'Reebok Zig Kinetica',
    price: 2290,
    originalPrice: 2690,
    imageUrl: 'https://5.imimg.com/data5/SELLER/Default/2022/6/UB/XP/UI/133556702/b3a8f52d-dd75-42cb-9ca5-85d36f15e223.jpg',
    discount: 15,
    categoryId: 'running',
    brand: 'Reebok',
    description: 'Advanced Reebok Zig Kinetica runners',
    stockQuantity: 5,
    tags: ['running', 'reebok', 'performance'],
    attributes: {
      'sizes': ['40', '41', '42', '43'],
      'colors': ['blue', 'yellow'],
    },
  ),
  Product(
    id: '6',
    name: 'Converse Chuck 70',
    price: 1890,
    originalPrice: 2190,
    imageUrl: 'https://www.converse.ph/media/catalog/product/cache/ae7cee22ac1ff58c2794c87414f27b45/0/8/0802-CONA08802C005013-1.jpg',
    discount: 14,
    categoryId: 'casual',
    brand: 'Converse',
    description: 'Classic Converse Chuck 70 sneakers',
    stockQuantity: 20,
    tags: ['casual', 'converse', 'classic'],
    attributes: {
      'sizes': ['40', '41', '42', '43'],
      'colors': ['white', 'black'],
    },
  ),
];
